const fs = require('fs');
const path = require('path');

class LuaGenerator {
  /**
   * Generate UpgradeData.lua file for WoW addon
   * @param {Object} upgrades Upgrade data keyed by item ID
   * @param {string} wowPath WoW installation path
   */
  static generateUpgradeData(upgrades, wowPath) {
    // Check for GearScore addon folder (current), fall back to GearSync (legacy)
    let addonPath = path.join(wowPath, 'Interface', 'AddOns', 'GearScore');
    if (!fs.existsSync(addonPath)) {
      addonPath = path.join(wowPath, 'Interface', 'AddOns', 'GearSync');
    }

    // Ensure addon directory exists
    if (!fs.existsSync(addonPath)) {
      fs.mkdirSync(addonPath, { recursive: true });
      console.log(`Created addon directory: ${addonPath}`);
    }

    const outputPath = path.join(addonPath, 'UpgradeData.lua');
    const luaContent = this.generateLuaTable(upgrades);

    fs.writeFileSync(outputPath, luaContent, 'utf8');
    console.log(`Generated UpgradeData.lua at: ${outputPath}`);

    return outputPath;
  }

  /**
   * Generate Lua table string from upgrade data
   * @param {Object} upgrades Upgrade data
   * @returns {string} Lua code
   */
  static generateLuaTable(upgrades) {
    let lua = '-- Auto-generated by TurtleLootLine Companion\n';
    lua += `-- Generated: ${new Date().toISOString()}\n`;
    lua += '-- Do not edit this file manually\n\n';
    lua += 'GearScoreUpgrades = {\n';

    const itemIds = Object.keys(upgrades).sort((a, b) => parseInt(a) - parseInt(b));

    for (const itemId of itemIds) {
      const data = upgrades[itemId];

      lua += `    [${itemId}] = {\n`;

      // Add each stat
      for (const [key, value] of Object.entries(data)) {
        const luaValue = this.toLuaValue(value);
        lua += `        ${key} = ${luaValue},\n`;
      }

      lua += '    },\n';
    }

    lua += '}\n';

    return lua;
  }

  /**
   * Convert JavaScript value to Lua value
   * @param {any} value Value to convert
   * @returns {string} Lua representation
   */
  static toLuaValue(value) {
    if (value === null || value === undefined) {
      return 'nil';
    }

    if (typeof value === 'string') {
      // Escape special characters
      const escaped = value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n');
      return `"${escaped}"`;
    }

    if (typeof value === 'number') {
      return value.toString();
    }

    if (typeof value === 'boolean') {
      return value ? 'true' : 'false';
    }

    if (typeof value === 'object' && !Array.isArray(value)) {
      // Nested table
      let lua = '{\n';
      for (const [k, v] of Object.entries(value)) {
        lua += `            ${k} = ${this.toLuaValue(v)},\n`;
      }
      lua += '        }';
      return lua;
    }

    if (Array.isArray(value)) {
      // Array
      let lua = '{\n';
      value.forEach((v, i) => {
        lua += `            [${i + 1}] = ${this.toLuaValue(v)},\n`;
      });
      lua += '        }';
      return lua;
    }

    return 'nil';
  }

  /**
   * Generate mock UpgradeData.lua for testing
   * @param {string} outputPath Path to write file
   */
  static generateMockUpgradeData(outputPath) {
    const mockData = {
      12640: { // Lionheart Helm
        stamina: '+15',
        armor: '+120',
        defense: '-2',
        overall: '+8.5%',
        note: 'BIS for Phase 2'
      },
      11726: { // Savage Gladiator Chain
        stamina: '+8',
        armor: '+80',
        overall: '+3.2%'
      },
      19019: { // Thunderfury
        stamina: '+12',
        attackPower: '+45',
        overall: '+12.8%',
        note: 'Legendary weapon'
      }
    };

    const luaContent = this.generateLuaTable(mockData);
    fs.writeFileSync(outputPath, luaContent, 'utf8');
    console.log(`Generated mock UpgradeData.lua at: ${outputPath}`);
  }
}

module.exports = LuaGenerator;
